### ISSUE TITLE
Depends on alsa-utils

### ISSUE THREAD

**Issue by rzr** [flatsiedatsie/internet-radio#4]
Hi, I've been trying this addon along deb package of webthing and noticed that alsactl was missing
So maybe you need to check if tool is present or run "apt-get install alsa-utils" on 1st install

Relate-to: https://magazine.odroid.com/article/webthings-on-armbian-using-the-odroid-xu4-for-the-internet-of-things/

**Comment by mrstegeman** [comment]
alsa-utils is listed as a recommended package for the deb.

**Comment by flatsiedatsie** [comment]
The add-on was originally designed to work on the Raspberry Pi only. If I can change anything to make it work more broadly, don't hesitate to create a pull request.

Come to think of it, I believe MrStegeman already did something like that.

**Comment by mrstegeman** [comment]
Correct, it should work basically anywhere now.
